databases:
  - name: pattask-db
    databaseName: pattask
    user: pattask_user
    region: Oregon

services:
  - type: web
    name: pattask
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pattask-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
